/* Website Deals - public package data. Admin edits (websiteDealsPackages) override these defaults. */
window.WDPackages={get:function(){
 var D=[
 {id:"starter",name:"Starter",badge:"Entry",price:549,period:"/month",status:true,sort:1,description:"A complete ready-made website for individuals, small businesses and local brands.",features:["Complete ready-made website","Free hosting + SSL","Basic logo","Fully responsive design","Custom domain connection","Contact form","bKash / Nagad / Bank payment","Basic SEO and support","Uptime monitoring"]},
 {id:"business",name:"Business",badge:"Most Popular",price:999,period:"/month",status:true,sort:2,description:"A stronger business website with admin panel, inquiries, analytics and integrations.",features:["Everything in Starter","Premium website design","Admin panel + Firebase","Online payment gateway","Product and service management","Inquiry and order management","WhatsApp / Messenger and Google Maps","Advanced SEO, Analytics, Search Console","Automated backup and priority support"]},
 {id:"premium",name:"Premium",badge:"Advanced",price:1999,period:"/month",status:true,sort:3,description:"A Shopify-style e-commerce system with inventory, orders, customers and custom workflows.",features:["Shopify-style e-commerce system","Advanced admin dashboard","Free stock and inventory management","Variants, SKU, coupons and discounts","Cart, checkout and order tracking","Customer accounts and management","Shipping, notifications, WhatsApp","API integration and custom workflows","Priority / dedicated support"]}];
 try{var r=JSON.parse(localStorage.getItem("websiteDealsPackages")||"null");if(Array.isArray(r)&&r.length)D=r}catch(e){}
 return D.filter(function(p){return p.status!==false}).sort(function(a,b){return (a.sort||0)-(b.sort||0)})},
 render:function(el,wa){
  function e(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
  el.innerHTML=this.get().map(function(p){var f=(p.features||[]),show=f.slice(0,9);
   var msg="Hello, I want the "+p.name+" package (৳"+p.price+(p.period||"")+")";
   return '<article class="pk'+(p.id==="business"?' hot':'')+'"><div class="pk-top"><h3>'+e(p.name)+'</h3>'+(p.badge?'<span class="pk-badge">'+e(p.badge)+'</span>':'')+'</div><p>'+e(p.description)+'</p><div class="pk-price">৳'+Number(p.price||0).toLocaleString("en-US")+'<small>'+e(p.period||"")+'</small></div><ul>'+show.map(function(x){return '<li>'+e(x)+'</li>'}).join("")+'</ul>'+(f.length>show.length?'<div class="pk-more">+ '+(f.length-show.length)+' more features</div>':'')+'<a class="btn '+(p.id==="business"?'dark':'lime')+'" target="_blank" rel="noopener" href="https://wa.me/'+wa+'?text='+encodeURIComponent(msg)+'">Subscribe on WhatsApp</a></article>'}).join("")}};
